In [1]:
import numpy as np

def rot(data, ang, erro, ponto):
    p = data.shape

    b = (p[0] - 1) / 2  # pega o meio da matriz
#     b = p[0] - 1  # pega o ultimo valor da matriz

    if ang == 90:
        alfa = np.tan(np.radians(ang)) * 1e20
    else:
        alfa = np.tan(np.radians(ang))

    b = b - alfa * b
    sel = []
    x = []
    y = []

    for i in range(0, p[0]):
        for j in range(0, p[1]):
            if b - erro <= j - alfa * i <= b + erro:
                x.append(i+ponto[0])
                y.append(j+ponto[1])
                sel.append(data[i, j])
    return x[0:np.count_nonzero(sel)], y[0:np.count_nonzero(sel)], sel[0:np.count_nonzero(sel)]

In [2]:
ord = 7  
data = np.zeros((ord, ord))
for i in range(0, ord):
    for j in range(0, ord):
        data[i, j] = '{}{}'.format(i+1, j+1)

ang = (ord ** 2 - ((ord - 2) ** 2))/2
for k in range(0, 180, 18):
    x, y, sel = rot(data[0: ord, 0: ord], k, 0.5, [0, 0])
    mt = np.zeros(data.shape)
    for i in range(0, len(sel)):
        mt[x[i], y[i]] = sel[i]

[[ 0.  0.  0. 14.  0.  0.  0.]
 [ 0.  0.  0. 24.  0.  0.  0.]
 [ 0.  0.  0. 34.  0.  0.  0.]
 [ 0.  0.  0. 44.  0.  0.  0.]
 [ 0.  0.  0. 54.  0.  0.  0.]
 [ 0.  0.  0. 64.  0.  0.  0.]
 [ 0.  0.  0. 74.  0.  0.  0.]] 0
[[ 0.  0. 13.  0.  0.  0.  0.]
 [ 0.  0. 23.  0.  0.  0.  0.]
 [ 0.  0.  0. 34.  0.  0.  0.]
 [ 0.  0.  0. 44.  0.  0.  0.]
 [ 0.  0.  0. 54.  0.  0.  0.]
 [ 0.  0.  0.  0. 65.  0.  0.]
 [ 0.  0.  0.  0. 75.  0.  0.]] 18
[[ 0. 12.  0.  0.  0.  0.  0.]
 [ 0.  0. 23.  0.  0.  0.  0.]
 [ 0.  0. 33.  0.  0.  0.  0.]
 [ 0.  0.  0. 44.  0.  0.  0.]
 [ 0.  0.  0.  0. 55.  0.  0.]
 [ 0.  0.  0.  0. 65.  0.  0.]
 [ 0.  0.  0.  0.  0. 76.  0.]] 36
[[ 0.  0.  0.  0.  0.  0.  0.]
 [21.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 33.  0.  0.  0.  0.]
 [ 0.  0.  0. 44.  0.  0.  0.]
 [ 0.  0.  0.  0. 55.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 67.]
 [ 0.  0.  0.  0.  0.  0.  0.]] 54
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [31.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 44.  0.  0